#配置文件

[website]
SITE_NAME = "Beaker"
SITE_URL = "-SITE_URL"
SITE_DES = "a simple blog system"
SITE_FOOTER = "Beaker is a simple blog system. [github.com/mebiusashan/beaker]"
SITE_KEYWORDS = "beaker, golang, blog"

#首页记录数量
INDEX_LIST_NUM = 30
TWEET_NUM_ONE_PAGE = 10
TEMP_FOLDER = "-TEMP_FOLDER/temp"
STATIC_FILE_FOLDER = "-STATIC_FILE_FOLDER/static/"

[server]
PORT = ":-PORT"
URL = "localhost"

[redis]
REDIS_IP = "127.0.0.1"
REDIS_PORT = "6379"
REDIS_PREFIX = "beaker_"
#设置7天的记录生命
EXPIRE_TIME = 25200

[database]
DB_URL = "-DB_URL"
DB_USER = "-DB_USER"
DB_PW = "-DB_PW"
DB_NAME = "-DB_NAME"
MAX_IDLE_NUM = 10
MAX_OPEN_NUM = 100